apiVersion: v1
kind: PersistentVolume
metadata:
  name: jw-base-pv
  namespace: jw
spec:
  storageClassName: local-storage
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 2G
  local:
    path: /data/jw-base
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - jw
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jw-base-pvc
  namespace: jw
spec:
  storageClassName: local-storage
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2G
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jw-base
  namespace: jw
spec:
  replicas: 1      #停用或启用某个dep的方法是把replicas设为0
  selector:
    matchLabels:
      app: jw-base    # 用于用label匹配  xxx -l app=nginx-pod
  template:
    metadata:
      labels:
        app: jw-base
    spec:
      containers:
      - name: jw-base
        image: www.jwdouble.top:10443/k8s/jw-base:202207191546
        ports:
        - containerPort: 10000
        env:
          - name: COMMON_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: jw-secret
                key: common_password
        volumeMounts:
        - mountPath: static
          name: jw-base-pv
      volumes:
      - name: jw-base-pv
        persistentVolumeClaim:
          claimName: jw-base-pvc


---
apiVersion: v1
kind: Service
metadata:
  name: jw-base-svc
  namespace: jw
  labels:
    name: jw-base-svc
spec:
  type: LoadBalancer
  ports:
  - name: http
    protocol: TCP
    port: 10000
    targetPort: 10000
  - name: https
    protocol: TCP
    port: 20000
    targetPort: 20000
  selector:
    app: jw-base
