apiVersion: v1
kind: PersistentVolume
metadata:
  name: pg-pv

spec:
  storageClassName: local-storage
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2G
  local:
    path: /file/
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: node-master
              operator: In
              values:
                - selector-master
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pg-pvc

spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2G
